In [1]:
import numpy as np


In [10]:
a=np.zeros((4,3,3))

In [11]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
np.ones((2,2,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [16]:
np.full((2,2),"hello")

array([['hello', 'hello'],
       ['hello', 'hello']], dtype='<U5')

In [23]:
np.random.rand(10)

array([0.37300411, 0.75427216, 0.54238359, 0.77301985, 0.95111739,
       0.40633218, 0.68134701, 0.00222025, 0.83485512, 0.57901464])

In [31]:
data=np.random.randint(5,10,(10,10))

In [32]:
data

array([[5, 9, 8, 7, 8, 8, 8, 6, 6, 5],
       [7, 6, 7, 8, 7, 5, 5, 9, 7, 8],
       [7, 5, 5, 7, 5, 5, 8, 5, 7, 5],
       [7, 8, 6, 8, 5, 5, 5, 9, 8, 6],
       [8, 7, 7, 5, 9, 9, 5, 7, 8, 9],
       [9, 7, 7, 8, 8, 9, 8, 6, 9, 8],
       [7, 8, 8, 6, 6, 8, 6, 9, 5, 5],
       [7, 5, 6, 9, 6, 6, 9, 6, 7, 5],
       [8, 8, 7, 8, 6, 6, 8, 6, 7, 7],
       [9, 6, 9, 8, 7, 5, 5, 7, 8, 5]])

In [33]:
data[4:8]

array([[8, 7, 7, 5, 9, 9, 5, 7, 8, 9],
       [9, 7, 7, 8, 8, 9, 8, 6, 9, 8],
       [7, 8, 8, 6, 6, 8, 6, 9, 5, 5],
       [7, 5, 6, 9, 6, 6, 9, 6, 7, 5]])

In [34]:
data[4:8,0:2]

array([[8, 7],
       [9, 7],
       [7, 8],
       [7, 5]])

In [35]:
data[4:8,4:8]

array([[9, 9, 5, 7],
       [8, 9, 8, 6],
       [6, 8, 6, 9],
       [6, 6, 9, 6]])

In [36]:
#combine data
data1=np.random.randint(5,15,size=(5,3))

In [38]:
data2=np.random.randint(5,15,size=(5,3))

In [39]:
np.hstack([data1,data2])

array([[13, 11,  7,  6,  9,  6],
       [ 7,  7, 13, 13, 10,  7],
       [ 8, 13, 13, 11,  7,  7],
       [ 5, 11, 10,  8,  9, 10],
       [ 6, 13, 11, 12, 12,  7]])

In [41]:
np.vstack([data1,data2])

array([[13, 11,  7],
       [ 7,  7, 13],
       [ 8, 13, 13],
       [ 5, 11, 10],
       [ 6, 13, 11],
       [ 6,  9,  6],
       [13, 10,  7],
       [11,  7,  7],
       [ 8,  9, 10],
       [12, 12,  7]])

In [43]:
np.concatenate([data1,data2],axis=1)

array([[13, 11,  7,  6,  9,  6],
       [ 7,  7, 13, 13, 10,  7],
       [ 8, 13, 13, 11,  7,  7],
       [ 5, 11, 10,  8,  9, 10],
       [ 6, 13, 11, 12, 12,  7]])

In [44]:
data1=np.random.randint(5,15,size=(5,3,2))

In [46]:
data2 = np.random.randint(5,15,size=(5,3,2))

In [56]:
np.concatenate([data1,data2],axis=2)

array([[[ 5,  6,  6,  5],
        [14,  8,  7, 11],
        [14,  5, 11,  5]],

       [[ 7, 11, 12,  5],
        [ 7, 13,  9, 14],
        [14, 14,  6,  8]],

       [[ 9, 12, 11, 13],
        [12, 14, 12, 12],
        [ 9, 11,  7, 10]],

       [[ 8,  8, 12, 12],
        [ 7, 10, 11, 11],
        [12, 12, 13,  7]],

       [[ 8,  9, 10,  6],
        [ 9,  6,  7,  5],
        [13, 14,  7, 13]]])

In [57]:
#splitting data
a1,a2=np.hsplit(data,[5])

In [59]:
data

array([[5, 9, 8, 7, 8, 8, 8, 6, 6, 5],
       [7, 6, 7, 8, 7, 5, 5, 9, 7, 8],
       [7, 5, 5, 7, 5, 5, 8, 5, 7, 5],
       [7, 8, 6, 8, 5, 5, 5, 9, 8, 6],
       [8, 7, 7, 5, 9, 9, 5, 7, 8, 9],
       [9, 7, 7, 8, 8, 9, 8, 6, 9, 8],
       [7, 8, 8, 6, 6, 8, 6, 9, 5, 5],
       [7, 5, 6, 9, 6, 6, 9, 6, 7, 5],
       [8, 8, 7, 8, 6, 6, 8, 6, 7, 7],
       [9, 6, 9, 8, 7, 5, 5, 7, 8, 5]])

In [61]:
a1

array([[5, 9, 8, 7, 8],
       [7, 6, 7, 8, 7],
       [7, 5, 5, 7, 5],
       [7, 8, 6, 8, 5],
       [8, 7, 7, 5, 9],
       [9, 7, 7, 8, 8],
       [7, 8, 8, 6, 6],
       [7, 5, 6, 9, 6],
       [8, 8, 7, 8, 6],
       [9, 6, 9, 8, 7]])

In [66]:
b1,b2,b3=np.vsplit(data,[2,7])

In [70]:
b3

array([[7, 5, 6, 9, 6, 6, 9, 6, 7, 5],
       [8, 8, 7, 8, 6, 6, 8, 6, 7, 7],
       [9, 6, 9, 8, 7, 5, 5, 7, 8, 5]])

In [71]:
#shape and dimension
data.shape

(10, 10)

In [72]:
data.ndim

2

In [73]:
data.size

100

In [74]:
data

array([[5, 9, 8, 7, 8, 8, 8, 6, 6, 5],
       [7, 6, 7, 8, 7, 5, 5, 9, 7, 8],
       [7, 5, 5, 7, 5, 5, 8, 5, 7, 5],
       [7, 8, 6, 8, 5, 5, 5, 9, 8, 6],
       [8, 7, 7, 5, 9, 9, 5, 7, 8, 9],
       [9, 7, 7, 8, 8, 9, 8, 6, 9, 8],
       [7, 8, 8, 6, 6, 8, 6, 9, 5, 5],
       [7, 5, 6, 9, 6, 6, 9, 6, 7, 5],
       [8, 8, 7, 8, 6, 6, 8, 6, 7, 7],
       [9, 6, 9, 8, 7, 5, 5, 7, 8, 5]])

In [76]:
data.reshape(5,20)

array([[5, 9, 8, 7, 8, 8, 8, 6, 6, 5, 7, 6, 7, 8, 7, 5, 5, 9, 7, 8],
       [7, 5, 5, 7, 5, 5, 8, 5, 7, 5, 7, 8, 6, 8, 5, 5, 5, 9, 8, 6],
       [8, 7, 7, 5, 9, 9, 5, 7, 8, 9, 9, 7, 7, 8, 8, 9, 8, 6, 9, 8],
       [7, 8, 8, 6, 6, 8, 6, 9, 5, 5, 7, 5, 6, 9, 6, 6, 9, 6, 7, 5],
       [8, 8, 7, 8, 6, 6, 8, 6, 7, 7, 9, 6, 9, 8, 7, 5, 5, 7, 8, 5]])

In [77]:
d=np.array([1,2,3,4,5,6,7,8,9])

In [78]:
d.ndim

1

In [83]:
d.shape

(9,)

In [84]:
d.size

9

In [85]:
d.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [86]:
data.reshape(-1,20)

array([[5, 9, 8, 7, 8, 8, 8, 6, 6, 5, 7, 6, 7, 8, 7, 5, 5, 9, 7, 8],
       [7, 5, 5, 7, 5, 5, 8, 5, 7, 5, 7, 8, 6, 8, 5, 5, 5, 9, 8, 6],
       [8, 7, 7, 5, 9, 9, 5, 7, 8, 9, 9, 7, 7, 8, 8, 9, 8, 6, 9, 8],
       [7, 8, 8, 6, 6, 8, 6, 9, 5, 5, 7, 5, 6, 9, 6, 6, 9, 6, 7, 5],
       [8, 8, 7, 8, 6, 6, 8, 6, 7, 7, 9, 6, 9, 8, 7, 5, 5, 7, 8, 5]])

In [87]:
data

array([[5, 9, 8, 7, 8, 8, 8, 6, 6, 5],
       [7, 6, 7, 8, 7, 5, 5, 9, 7, 8],
       [7, 5, 5, 7, 5, 5, 8, 5, 7, 5],
       [7, 8, 6, 8, 5, 5, 5, 9, 8, 6],
       [8, 7, 7, 5, 9, 9, 5, 7, 8, 9],
       [9, 7, 7, 8, 8, 9, 8, 6, 9, 8],
       [7, 8, 8, 6, 6, 8, 6, 9, 5, 5],
       [7, 5, 6, 9, 6, 6, 9, 6, 7, 5],
       [8, 8, 7, 8, 6, 6, 8, 6, 7, 7],
       [9, 6, 9, 8, 7, 5, 5, 7, 8, 5]])

In [91]:
#utility function
np.sum(data)

692

In [92]:
np.sum(data,axis=0)

array([74, 69, 70, 74, 67, 66, 67, 70, 72, 63])

In [93]:
np.sum(data,axis=1)

array([70, 69, 59, 67, 74, 79, 68, 66, 71, 69])

In [94]:
np.sin(data)

array([[-0.95892427,  0.41211849,  0.98935825,  0.6569866 ,  0.98935825,
         0.98935825,  0.98935825, -0.2794155 , -0.2794155 , -0.95892427],
       [ 0.6569866 , -0.2794155 ,  0.6569866 ,  0.98935825,  0.6569866 ,
        -0.95892427, -0.95892427,  0.41211849,  0.6569866 ,  0.98935825],
       [ 0.6569866 , -0.95892427, -0.95892427,  0.6569866 , -0.95892427,
        -0.95892427,  0.98935825, -0.95892427,  0.6569866 , -0.95892427],
       [ 0.6569866 ,  0.98935825, -0.2794155 ,  0.98935825, -0.95892427,
        -0.95892427, -0.95892427,  0.41211849,  0.98935825, -0.2794155 ],
       [ 0.98935825,  0.6569866 ,  0.6569866 , -0.95892427,  0.41211849,
         0.41211849, -0.95892427,  0.6569866 ,  0.98935825,  0.41211849],
       [ 0.41211849,  0.6569866 ,  0.6569866 ,  0.98935825,  0.98935825,
         0.41211849,  0.98935825, -0.2794155 ,  0.41211849,  0.98935825],
       [ 0.6569866 ,  0.98935825,  0.98935825, -0.2794155 , -0.2794155 ,
         0.98935825, -0.2794155 ,  0.41211849

In [95]:
data.T

array([[5, 7, 7, 7, 8, 9, 7, 7, 8, 9],
       [9, 6, 5, 8, 7, 7, 8, 5, 8, 6],
       [8, 7, 5, 6, 7, 7, 8, 6, 7, 9],
       [7, 8, 7, 8, 5, 8, 6, 9, 8, 8],
       [8, 7, 5, 5, 9, 8, 6, 6, 6, 7],
       [8, 5, 5, 5, 9, 9, 8, 6, 6, 5],
       [8, 5, 8, 5, 5, 8, 6, 9, 8, 5],
       [6, 9, 5, 9, 7, 6, 9, 6, 6, 7],
       [6, 7, 7, 8, 8, 9, 5, 7, 7, 8],
       [5, 8, 5, 6, 9, 8, 5, 5, 7, 5]])

In [96]:
data.mean(axis=1)

array([7. , 6.9, 5.9, 6.7, 7.4, 7.9, 6.8, 6.6, 7.1, 6.9])

In [97]:
data.std(axis=1)

array([1.34164079, 1.22065556, 1.13578167, 1.41774469, 1.42828569,
       0.94339811, 1.32664992, 1.356466  , 0.83066239, 1.5132746 ])

In [99]:
#broadcasting
v=np.array([1,2,3,4,5])

In [100]:
s=10

In [101]:
v+s

array([11, 12, 13, 14, 15])

In [102]:
t=[10,11]

In [104]:
a=np.array([[1],[2],[3],[4],[5]])

In [106]:
a.shape

(5, 1)

In [107]:
a+v

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [109]:
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [110]:
v

array([1, 2, 3, 4, 5])

In [111]:
a=np.random.randint(1,5,size=(10,2))

In [113]:
b=np.random.randint(1,5,size=(5,2))

In [116]:
a

array([[1, 4],
       [1, 4],
       [1, 1],
       [2, 1],
       [3, 4],
       [4, 1],
       [1, 3],
       [2, 1],
       [3, 3],
       [2, 2]])

In [117]:
a.reshape(1,10,2)

array([[[1, 4],
        [1, 4],
        [1, 1],
        [2, 1],
        [3, 4],
        [4, 1],
        [1, 3],
        [2, 1],
        [3, 3],
        [2, 2]]])

In [118]:
b

array([[1, 2],
       [1, 3],
       [1, 4],
       [1, 4],
       [3, 1]])

In [121]:
b.reshape(5,1,2)

array([[[1, 2]],

       [[1, 3]],

       [[1, 4]],

       [[1, 4]],

       [[3, 1]]])

In [122]:
b.reshape(5,1,2)-a.reshape(1,10,2)

array([[[ 0, -2],
        [ 0, -2],
        [ 0,  1],
        [-1,  1],
        [-2, -2],
        [-3,  1],
        [ 0, -1],
        [-1,  1],
        [-2, -1],
        [-1,  0]],

       [[ 0, -1],
        [ 0, -1],
        [ 0,  2],
        [-1,  2],
        [-2, -1],
        [-3,  2],
        [ 0,  0],
        [-1,  2],
        [-2,  0],
        [-1,  1]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  3],
        [-1,  3],
        [-2,  0],
        [-3,  3],
        [ 0,  1],
        [-1,  3],
        [-2,  1],
        [-1,  2]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  3],
        [-1,  3],
        [-2,  0],
        [-3,  3],
        [ 0,  1],
        [-1,  3],
        [-2,  1],
        [-1,  2]],

       [[ 2, -3],
        [ 2, -3],
        [ 2,  0],
        [ 1,  0],
        [ 0, -3],
        [-1,  0],
        [ 2, -2],
        [ 1,  0],
        [ 0, -2],
        [ 1, -1]]])

In [123]:
a=np.random.randint(1,5,size=(10,2))

In [125]:
b=np.random.randint(1,5,size=(5,3))

In [126]:
a.shape

(10, 2)

In [127]:
b.shape

(5, 3)

In [130]:
b

array([[2, 1, 3],
       [3, 3, 1],
       [4, 1, 3],
       [2, 1, 3],
       [2, 3, 3]])

In [131]:
a.reshape(1,10,1,2)-b.reshape(5,1,3,1)

array([[[[ 0,  2],
         [ 1,  3],
         [-1,  1]],

        [[-1,  2],
         [ 0,  3],
         [-2,  1]],

        [[ 1,  0],
         [ 2,  1],
         [ 0, -1]],

        [[ 2,  2],
         [ 3,  3],
         [ 1,  1]],

        [[ 0,  0],
         [ 1,  1],
         [-1, -1]],

        [[ 2,  1],
         [ 3,  2],
         [ 1,  0]],

        [[ 1,  0],
         [ 2,  1],
         [ 0, -1]],

        [[ 1,  1],
         [ 2,  2],
         [ 0,  0]],

        [[ 2,  0],
         [ 3,  1],
         [ 1, -1]],

        [[ 0, -1],
         [ 1,  0],
         [-1, -2]]],


       [[[-1,  1],
         [-1,  1],
         [ 1,  3]],

        [[-2,  1],
         [-2,  1],
         [ 0,  3]],

        [[ 0, -1],
         [ 0, -1],
         [ 2,  1]],

        [[ 1,  1],
         [ 1,  1],
         [ 3,  3]],

        [[-1, -1],
         [-1, -1],
         [ 1,  1]],

        [[ 1,  0],
         [ 1,  0],
         [ 3,  2]],

        [[ 0, -1],
         [ 0, -1],
         [ 2,  1