## Exercise

**Q1- Write a NumPy code to calculate the missing sum row wise and column wise in below data matrix**

In [1]:
#Write your code here
import numpy as np
np.random.seed(42)
data=np.random.randn(10,5)
data[data<-1]=np.nan
data

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227,         nan,         nan],
       [-0.56228753,         nan,  0.31424733, -0.90802408,         nan],
       [ 1.46564877, -0.2257763 ,  0.0675282 ,         nan, -0.54438272],
       [ 0.11092259,         nan,  0.37569802, -0.60063869, -0.29169375],
       [-0.60170661,  1.85227818, -0.01349722,         nan,  0.82254491],
       [        nan,  0.2088636 ,         nan,         nan,  0.19686124],
       [ 0.73846658,  0.17136828, -0.11564828, -0.3011037 ,         nan],
       [-0.71984421, -0.46063877,  1.05712223,  0.34361829,         nan]])

In [2]:
#write ans here

**Q2- Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10** <br>

Output-  <br>
 [[100 110] <br>
 [120 130] <br>
 [140 150] <br>
 [160 170] <br>
 [180 190]]

In [3]:
##Write your code here

**Q3- Sort the following array**
- arr = array([[5,6,4],[2,5,1],[9,4,1]]).reshape(3,3)

**Output** - 
array(<br>[[4, 5, 6], <br>[1, 2, 5], <br>     [1, 4, 9]])

In [4]:
##Write your code here

**Q4- Create and array and replace all the odd numbers in arr with −1 without changing arr:**

In [5]:
##Write your code here

**Q5- Given an array** <br>
arr = np.arange(10) <br>
Use slicing to find elements **4,5,6**. Define it in an array called arr_subset.

In [51]:
##Write your code here

**Q6- Using the previous result, 2nd element of arr_subset to 65. What is the effect on the original array “arr”?**

In [52]:
##Write your code here

**Q7- What will be the output of “arr” if** <br>
arr_subset[:] = 99

PLEASE DON'T CODE

In [53]:
#Write your answer here:

**Q8- Given an array** <br>
arr = np.array([[[1,2,3],[4,5,6]],[7,8,9]])

What will be the output of arr[0][0]?

PLEASE DON'T CODE

In [54]:
#Write your answer here:

**Q9: Add the following two NumPy arrays and Modify a result array by calculating the square of each element** <br>

arr1 = numpy.array([[5, 6, 9], [21 ,18, 27]]) <br>
arr2 = numpy.array([[15 ,33, 24], [4 ,7, 1]]) <br>

Output - <br>
[[ 400 1521 1089] <br>
 [ 625  625  784]]

In [55]:
#Write your code here:

**Q10- Given the arrays** <br>

arr1 = np.arange(5,10,1) <br>
arr2 = np.arange(-5,0,1) <br>
cond = np.array([True,False,False,False,True]) <br>

Create a new array called arr3 and input the value of arr1 wherever cond = True else input arr2. <br>

Output - array([ 5, -4, -3, -2,  9])

In [56]:
#Write your code here:

**Q11- Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.**

arr = np.array([0 0 3 0 2 4 2 2 2 2])

Desired output- 

array([False  True False  True False False  True  True  True  True])

In [57]:
#Write your code here:

### Additional Exercises

**Q1- Given two arrays:**

arr1 = np.array([range(9)]).reshape(2,-1) <br>
arr2 = np.repeat(1,10).reshape(2,-1) <br>

Concatenate the two arrays by rows.

In [58]:
#Write your code here:

**Q2- What will be the output?**

arr1 = np.arange(9) <br>
arr1_copy = arr1.copy() <br>
arr2 = arr1_copy[4:7] <br>
arr2[1]=45 <br>
arr1 <br>

PLEASE DON'T CODE

In [59]:
#Write your answer here:

**Q3- What is the output?**

arr1 = np.arange(5) <br>
arr2 = np.array([[1,2,3],[4,5,6],[2,3,4],[7,8,0],[0,0,0]]) <br>
arr2[arr1 == 1]

PLEAESE DON'T CODE

In [60]:
#Write your answer here:

**Q4- Given an array**

arr = np.randon.randn(4,4)
Calculate the following:

1. Mean
2. Max
3. Sum
4. Standard Deviation
5. cumsum

In [61]:
#Write your code here:

**Q5- Get the common items between a and b:**

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6]) <br>
b = np.array([7,2,10,2,7,4,9,4,9,8])<br>

Desired output:

array([2, 4])

In [62]:
#Write your code here: