## Exercise

**Q1- Write a NumPy code to calculate the missing sum row wise and column wise in below data matrix**

In [84]:
#Write your code here
import numpy as np
np.random.seed(42)
data=np.random.randn(10,5)
data[data<-1]=np.nan
data

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227,         nan,         nan],
       [-0.56228753,         nan,  0.31424733, -0.90802408,         nan],
       [ 1.46564877, -0.2257763 ,  0.0675282 ,         nan, -0.54438272],
       [ 0.11092259,         nan,  0.37569802, -0.60063869, -0.29169375],
       [-0.60170661,  1.85227818, -0.01349722,         nan,  0.82254491],
       [        nan,  0.2088636 ,         nan,         nan,  0.19686124],
       [ 0.73846658,  0.17136828, -0.11564828, -0.3011037 ,         nan],
       [-0.71984421, -0.46063877,  1.05712223,  0.34361829,         nan]])

In [85]:
np.sum(np.isnan(data),axis=0)

array([1, 2, 1, 4, 4])

In [86]:
np.sum(np.isnan(data),axis=1)

array([0, 0, 2, 2, 1, 1, 1, 3, 1, 1])

**Q2- Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10** <br>

Output-  <br>
 [[100 110] <br>
 [120 130] <br>
 [140 150] <br>
 [160 170] <br>
 [180 190]]

In [71]:
##Write your code here
np.arange(100,200,10).reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

**Q3- Sort the following array**
- arr = array([[5,6,4],[2,5,1],[9,4,1]]).reshape(3,3)

**Output** - 
array(<br>[[4, 5, 6], <br>[1, 2, 5], <br>     [1, 4, 9]])

In [72]:
##Write your code here
arr = np.array([[5,6,4],[2,5,1],[9,4,1]]).reshape(3,3)
np.sort(arr)

array([[4, 5, 6],
       [1, 2, 5],
       [1, 4, 9]])

**Q4- Create and array and replace all the odd numbers in arr with −1 without changing arr:**

In [73]:
##Write your code here

#method 1
arr = np.arange(10)
arr2 = [-1 if arr%2 != 0 else arr for arr in arr]
print("Method 1")
print("New Array: ", arr2)
print("Original Array: ", arr)
print(' ')

#method 2
arr = np.arange(10)
arr2 = np.where(arr%2 != 0, -1, arr)
print("Method 2")
print("New Array: ", arr2)
print("Original Array: ", arr)

Method 1
New Array:  [0, -1, 2, -1, 4, -1, 6, -1, 8, -1]
Original Array:  [0 1 2 3 4 5 6 7 8 9]
 
Method 2
New Array:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Original Array:  [0 1 2 3 4 5 6 7 8 9]


**Q5- Given an array** <br>
arr = np.arange(10) <br>
Use slicing to find elements **4,5,6**. Define it in an array called arr_subset.

In [74]:
##Write your code here
arr = np.arange(10)
arr_subset = arr[4:7]
arr_subset

array([4, 5, 6])

**Q6- Using the previous result, 2nd element of arr_subset to 65. What is the effect on the original array “arr”?**

In [75]:
##Write your code here
arr_subset[1] = 65
print("arr_subset: ", arr_subset)
print("arr: ", arr)

arr_subset:  [ 4 65  6]
arr:  [ 0  1  2  3  4 65  6  7  8  9]


**Q7- What will be the output of “arr” if** <br>
arr_subset[:] = 99

PLEASE DON'T CODE

#Write your answer here: <br>
**Answer-** array([99, 99, 99])

**Q8- Given an array** <br>
arr = np.array([[[1,2,3],[4,5,6]],[7,8,9]])

What will be the output of arr[0][0]?

PLEASE DON'T CODE

#Write your answer here:<br>
**Answer-** [1, 2, 3]

**Q9: Add the following two NumPy arrays and Modify a result array by calculating the square of each element** <br>

arr1 = np.array([[5, 6, 9], [21 ,18, 27]]) <br>
arr2 = np.array([[15 ,33, 24], [4 ,7, 1]]) <br>

Output - <br>
[[ 400 1521 1089] <br>
 [ 625  625  784]]

In [76]:
#Write your code here:
arr1 = np.array([[5, 6, 9], [21 ,18, 27]])
arr2 = np.array([[15 ,33, 24], [4 ,7, 1]])
arr3 = np.add(arr1, arr2)
arr3*arr3

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

**Q10- Given the arrays** <br>

arr1 = np.arange(5,10,1) <br>
arr2 = np.arange(-5,0,1) <br>
cond = np.array([True,False,False,False,True]) <br>

Create a new array called arr3 and input the value of arr1 wherever cond = True else input arr2. <br>

Output - array([ 5, -4, -3, -2,  9])

In [77]:
#Write your code here:
arr1 = np.arange(5,10,1)
arr2 = np.arange(-5,0,1)
cond = np.array([True,False,False,False,True])
arr3 = np.where(cond == True, arr1, arr2)
arr3

array([ 5, -4, -3, -2,  9])

**Q11- Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.**

arr = np.array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

Desired output- 

array([False  True False  True False False  True  True  True  True])

In [78]:
#Write your code here:

arr = np.array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

# Create an all True array
out = np.full(arr.shape[0], True)

# Find the index positions of unique elements
unique_positions = np.unique(arr, return_index=True)[1]

# Mark those positions as False
out[unique_positions] = False
out

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

In [79]:
pos=0
unique=np.unique(arr)
for each in arr:    
    if each in unique:
        print(pos)
        unique=unique[unique!=each]
        #print(unique)
    pos+=1
        

0
2
4
5


#################################################### End of Session ##########################################################

### Additional Exercises

**Q1- Given two arrays:**

arr1 = np.array([range(9)]).reshape(2,-1) <br>
arr2 = np.repeat(1,10).reshape(2,-1) <br>

Concatenate the two arrays by rows.

In [80]:
#Write your code here:
arr1 = np.array([range(8)]).reshape(2,-1)
arr2 = np.repeat(1,8).reshape(2,-1)
np.concatenate((arr1, arr2), axis = 0)

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

**Q2- What will be the output?**

arr1 = np.arange(9) <br>
arr1_copy = arr1.copy() <br>
arr2 = arr1_copy[4:7] <br>
arr2[1]=45 <br>
arr1 <br>

PLEASE DON'T CODE

#Write your answer here: <br>
**Answer-** array([0, 1, 2, 3, 4, 5, 6, 7, 8])

**Q3- What is the output?**

arr1 = np.arange(5) <br>
arr2 = np.array([[1,2,3],[4,5,6],[2,3,4],[7,8,0],[0,0,0]]) <br>
arr2[arr1 == 1]

PLEAESE DON'T CODE

#Write your answer here: <br>
**Answer-** array([[4, 5, 6]])

**Q4- Given an array**

arr = np.randon.randn(4,4)
Calculate the following:

1. Mean
2. Max
3. Sum
4. Standard Deviation
5. cumsum

In [81]:
#Write your code here:
arr = np.random.randn(4,4)
print(arr)
print(' ')
print("Mean", np.mean(arr))
print(' ')
print("Max", np.max(arr))
print(' ')
print("Sum", np.sum(arr))
print(' ')
print("Std", np.std(arr))
print(' ')
print("cumsum", np.cumsum(arr))

[[ 0.32408397 -0.38508228 -0.676922    0.61167629]
 [ 1.03099952  0.93128012 -0.83921752 -0.30921238]
 [ 0.33126343  0.97554513 -0.47917424 -0.18565898]
 [-1.10633497 -1.19620662  0.81252582  1.35624003]]
 
Mean 0.07473783230917637
 
Max 1.356240028570823
 
Sum 1.195805316946822
 
Std 0.7986877023054441
 
cumsum [ 0.32408397 -0.06099831 -0.73792031 -0.12624402  0.9047555   1.83603562
  0.9968181   0.68760572  1.01886915  1.99441428  1.51524004  1.32958106
  0.22324609 -0.97296053 -0.16043471  1.19580532]


**Q5- Get the common items between a and b:**

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6]) <br>
b = np.array([7,2,10,2,7,4,9,4,9,8])<br>

Desired output:

array([2, 4])

In [82]:
#Write your code here:

#Method 1
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Method 1")
print(np.intersect1d(a,b))
print(' ')

#Method 2
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Method 2")
print(np.unique(a[a==b]))

Method 1
[2 4]
 
Method 2
[2 4]


In [83]:

def outlierRemover(arr):
    lowerValue=np.percentile(arr,25)
    upperValue=np.percentile(arr,75)
    iqr=upperValue-lowerValue
    
    arr=arr[(arr>(lowerValue-1.5*(iqr))) & (arr<(upperValue+1.5*(iqr)))]
    return arr

print(arr)
outlierRemover(arr)

[[ 0.32408397 -0.38508228 -0.676922    0.61167629]
 [ 1.03099952  0.93128012 -0.83921752 -0.30921238]
 [ 0.33126343  0.97554513 -0.47917424 -0.18565898]
 [-1.10633497 -1.19620662  0.81252582  1.35624003]]


array([ 0.32408397, -0.38508228, -0.676922  ,  0.61167629,  1.03099952,
        0.93128012, -0.83921752, -0.30921238,  0.33126343,  0.97554513,
       -0.47917424, -0.18565898, -1.10633497, -1.19620662,  0.81252582,
        1.35624003])