In [3]:
import numpy as np
import xgboost as xgb
from xgboost.sklearn import XGBClassifier
from sklearn.cross_validation import cross_val_score
seed=123

In [5]:
np.random.seed(seed)
data_v=np.random.rand(10,5)
data_v

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897],
       [0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752],
       [0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176, 0.53155137, 0.53182759],
       [0.63440096, 0.84943179, 0.72445532, 0.61102351, 0.72244338],
       [0.32295891, 0.36178866, 0.22826323, 0.29371405, 0.63097612],
       [0.09210494, 0.43370117, 0.43086276, 0.4936851 , 0.42583029],
       [0.31226122, 0.42635131, 0.89338916, 0.94416002, 0.50183668],
       [0.62395295, 0.1156184 , 0.31728548, 0.41482621, 0.86630916],
       [0.25045537, 0.48303426, 0.98555979, 0.51948512, 0.61289453]])

In [8]:
data_m=np.copy(data_v)
data_m[2, 3] = np.nan
data_m[0, 1] = np.nan
data_m[0, 2] = np.nan
data_m[1, 0] = np.nan
data_m[4, 4] = np.nan
data_m[7, 2] = np.nan
data_m[9, 1] = np.nan

data_m

array([[0.69646919,        nan,        nan, 0.55131477, 0.71946897],
       [       nan, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752],
       [0.34317802, 0.72904971, 0.43857224,        nan, 0.39804426],
       [0.73799541, 0.18249173, 0.17545176, 0.53155137, 0.53182759],
       [0.63440096, 0.84943179, 0.72445532, 0.61102351,        nan],
       [0.32295891, 0.36178866, 0.22826323, 0.29371405, 0.63097612],
       [0.09210494, 0.43370117, 0.43086276, 0.4936851 , 0.42583029],
       [0.31226122, 0.42635131,        nan, 0.94416002, 0.50183668],
       [0.62395295, 0.1156184 , 0.31728548, 0.41482621, 0.86630916],
       [0.25045537,        nan, 0.98555979, 0.51948512, 0.61289453]])

In [11]:
label=np.random.randint(2,size=10)
label

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [12]:
# specify general training parameters
params = {
    'objective':'binary:logistic',
    'max_depth':1,
    'silent':1,
    'eta':0.5
}

num_rounds = 5

In [13]:
dtrain_v=xgb.DMatrix(data_v,label=label)

In [19]:
xgb.cv(params,dtrain_v,num_rounds,seed=seed)

train-error-mean  train-error-std  test-error-mean  test-error-std
0          0.198413         0.062492         0.194444        0.141639
1          0.198413         0.062492         0.194444        0.141639
2          0.198413         0.062492         0.194444        0.141639
3          0.198413         0.062492         0.194444        0.141639
4          0.198413         0.062492         0.194444        0.141639

In [20]:
dtrain_m = xgb.DMatrix(data_m, label=label, missing=np.nan)

In [21]:
xgb.cv(params, dtrain_m, num_rounds, seed=seed)

train-error-mean  train-error-std  test-error-mean  test-error-std
0          0.198413         0.062492         0.194444        0.141639
1          0.198413         0.062492         0.194444        0.141639
2          0.198413         0.062492         0.194444        0.141639
3          0.198413         0.062492         0.194444        0.141639
4          0.198413         0.062492         0.194444        0.141639

In [22]:
params = {
    'objective': 'binary:logistic',
    'max_depth': 1,
    'learning_rate': 0.5,
    'silent': 1.0,
    'n_estimators': 5
}


In [23]:
clf = XGBClassifier(**params)
clf

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.5, max_delta_step=0,
       max_depth=1, min_child_weight=1, missing=None, n_estimators=5,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=1.0, subsample=1)

In [24]:
cross_val_score(clf, data_v, label, cv=2, scoring='accuracy')

array([0.8, 0.8])

In [25]:
cross_val_score(clf, data_m, label, cv=2, scoring='accuracy')

array([0.8, 0.8])